"""
    Boson v0.1
    By: ict
    Email: ictxiangxin@gmail.com

    This code generated by boson python code generator.
    You need fill some reduce code to let it available.
"""


terminal_index = {
    "br":    0,
    "float": 1,
    "bl":    2,
    "div":   3,
    "power": 4,
    "int":   5,
    "plus":  6,
    "times": 7,
    "minus": 8,
    "$":     9,
}

action_table = [
    ["e",   "s2",  "s4",  "e",   "e",   "s3",  "e",   "e",   "e",     "e"],
    ["e",   "e",   "e",   "s9",  "e",   "e",   "e",   "s10", "e",    "r4"],
    ["e",   "e",   "e",   "e",   "e",   "e",   "e",   "e",   "e",    "r7"],
    ["e",   "e",   "e",   "e",   "e",   "e",   "e",   "e",   "e",    "r8"],
    ["e",   "s12", "s14", "e",   "e",   "s13", "e",   "e",   "e",     "e"],
    ["e",   "e",   "e",   "e",   "s19", "e",   "e",   "e",   "e",    "r9"],
    ["e",   "e",   "e",   "e",   "e",   "e",   "s20", "e",   "s21",   "a"],
    ["e",   "e",   "e",   "e",   "e",   "e",   "e",   "e",   "e",   "r12"],
    ["e",   "e",   "e",   "e",   "e",   "e",   "e",   "e",   "e",    "r5"],
    ["e",   "s2",  "s4",  "e",   "e",   "s3",  "e",   "e",   "e",     "e"],
    ["e",   "s2",  "s4",  "e",   "e",   "s3",  "e",   "e",   "e",     "e"],
    ["r4",  "e",   "e",   "s24", "e",   "e",   "e",   "s25", "e",     "e"],
    ["r7",  "e",   "e",   "e",   "e",   "e",   "e",   "e",   "e",     "e"],
    ["r8",  "e",   "e",   "e",   "e",   "e",   "e",   "e",   "e",     "e"],
    ["e",   "s12", "s14", "e",   "e",   "s13", "e",   "e",   "e",     "e"],
    ["r9",  "e",   "e",   "e",   "s27", "e",   "e",   "e",   "e",     "e"],
    ["s29", "e",   "e",   "e",   "e",   "e",   "s28", "e",   "s30",   "e"],
    ["r12", "e",   "e",   "e",   "e",   "e",   "e",   "e",   "e",     "e"],
    ["r5",  "e",   "e",   "e",   "e",   "e",   "e",   "e",   "e",     "e"],
    ["e",   "s2",  "s4",  "e",   "e",   "s3",  "e",   "e",   "e",     "e"],
    ["e",   "s2",  "s4",  "e",   "e",   "s3",  "e",   "e",   "e",     "e"],
    ["e",   "s2",  "s4",  "e",   "e",   "s3",  "e",   "e",   "e",     "e"],
    ["e",   "e",   "e",   "e",   "s19", "e",   "e",   "e",   "e",   "r10"],
    ["e",   "e",   "e",   "e",   "s19", "e",   "e",   "e",   "e",   "r11"],
    ["e",   "s12", "s14", "e",   "e",   "s13", "e",   "e",   "e",     "e"],
    ["e",   "s12", "s14", "e",   "e",   "s13", "e",   "e",   "e",     "e"],
    ["s36", "e",   "e",   "e",   "e",   "e",   "s28", "e",   "s30",   "e"],
    ["e",   "s12", "s14", "e",   "e",   "s13", "e",   "e",   "e",     "e"],
    ["e",   "s12", "s14", "e",   "e",   "s13", "e",   "e",   "e",     "e"],
    ["e",   "e",   "e",   "e",   "e",   "e",   "e",   "e",   "e",    "r1"],
    ["e",   "s12", "s14", "e",   "e",   "s13", "e",   "e",   "e",     "e"],
    ["e",   "e",   "e",   "e",   "e",   "e",   "e",   "e",   "e",    "r6"],
    ["e",   "e",   "e",   "s9",  "e",   "e",   "e",   "s10", "e",    "r3"],
    ["e",   "e",   "e",   "s9",  "e",   "e",   "e",   "s10", "e",    "r2"],
    ["r10", "e",   "e",   "e",   "s27", "e",   "e",   "e",   "e",     "e"],
    ["r11", "e",   "e",   "e",   "s27", "e",   "e",   "e",   "e",     "e"],
    ["r1",  "e",   "e",   "e",   "e",   "e",   "e",   "e",   "e",     "e"],
    ["r6",  "e",   "e",   "e",   "e",   "e",   "e",   "e",   "e",     "e"],
    ["r3",  "e",   "e",   "s24", "e",   "e",   "e",   "s25", "e",     "e"],
    ["r2",  "e",   "e",   "s24", "e",   "e",   "e",   "s25", "e",     "e"],
]

non_terminal_index = {
    "T": 0,
    "F": 1,
    "D": 2,
    "E": 3,
    "N": 4,
}

goto_table = [
    [1,  5,  8,  6,   7],
    [-1, -1, -1, -1, -1],
    [-1, -1, -1, -1, -1],
    [-1, -1, -1, -1, -1],
    [11, 15, 18, 16, 17],
    [-1, -1, -1, -1, -1],
    [-1, -1, -1, -1, -1],
    [-1, -1, -1, -1, -1],
    [-1, -1, -1, -1, -1],
    [-1, 22, 8,  -1,  7],
    [-1, 23, 8,  -1,  7],
    [-1, -1, -1, -1, -1],
    [-1, -1, -1, -1, -1],
    [-1, -1, -1, -1, -1],
    [11, 15, 18, 26, 17],
    [-1, -1, -1, -1, -1],
    [-1, -1, -1, -1, -1],
    [-1, -1, -1, -1, -1],
    [-1, -1, -1, -1, -1],
    [-1, -1, 31, -1,  7],
    [32, 5,  8,  -1,  7],
    [33, 5,  8,  -1,  7],
    [-1, -1, -1, -1, -1],
    [-1, -1, -1, -1, -1],
    [-1, 34, 18, -1, 17],
    [-1, 35, 18, -1, 17],
    [-1, -1, -1, -1, -1],
    [-1, -1, 37, -1, 17],
    [38, 15, 18, -1, 17],
    [-1, -1, -1, -1, -1],
    [39, 15, 18, -1, 17],
    [-1, -1, -1, -1, -1],
    [-1, -1, -1, -1, -1],
    [-1, -1, -1, -1, -1],
    [-1, -1, -1, -1, -1],
    [-1, -1, -1, -1, -1],
    [-1, -1, -1, -1, -1],
    [-1, -1, -1, -1, -1],
    [-1, -1, -1, -1, -1],
    [-1, -1, -1, -1, -1],
]

reduce_symbol_sum = {
    0:  1,
    1:  3,
    2:  3,
    3:  3,
    4:  1,
    5:  1,
    6:  3,
    7:  1,
    8:  1,
    9:  1,
    10: 3,
    11: 3,
    12: 1,
}

reduce_to_non_terminal = {
    0:  "start",
    1:  "D",
    2:  "E",
    3:  "E",
    4:  "E",
    5:  "F",
    6:  "F",
    7:  "N",
    8:  "N",
    9:  "T",
    10: "T",
    11: "T",
    12: "D",
}


def grammar_analysis(token_line):
    """
        Add some data structure definition code here...
    """
    stack = [0]
    token_index = 0
    while token_index < len(token_line):
        token = token_line[token_index]
        token_type = token[0]
        now_state = stack[-1]
        operation = action_table[now_state][terminal_index[token_type]]
        operation_flag = operation[0]
        if operation_flag == "e":
            raise Exception("Grammar error: " + " ".join([t[1] for t in token_line]))
        elif operation_flag == "s":
            operation_number = int(operation[1:])
            stack.append(operation_number)
            token_index += 1
            """
                Add some code for shift action here...
            """
        elif operation_flag == "r":
            operation_number = int(operation[1:])
            reduce_sum = reduce_symbol_sum[operation_number]
            for _ in range(reduce_sum):
                stack.pop()
            now_state = stack[-1]
            stack.append(goto_table[now_state][non_terminal_index[reduce_to_non_terminal[operation_number]]])
            if operation_number == 1:
                """
                    Add some code for reduce 1 here...
                    D -> bl E br
                """
                pass
            elif operation_number == 2:
                """
                    Add some code for reduce 2 here...
                    E -> E minus T
                """
                pass
            elif operation_number == 3:
                """
                    Add some code for reduce 3 here...
                    E -> E plus T
                """
                pass
            elif operation_number == 4:
                """
                    Add some code for reduce 4 here...
                    E -> T
                """
                pass
            elif operation_number == 5:
                """
                    Add some code for reduce 5 here...
                    F -> D
                """
                pass
            elif operation_number == 6:
                """
                    Add some code for reduce 6 here...
                    F -> F power D
                """
                pass
            elif operation_number == 7:
                """
                    Add some code for reduce 7 here...
                    N -> float
                """
                pass
            elif operation_number == 8:
                """
                    Add some code for reduce 8 here...
                    N -> int
                """
                pass
            elif operation_number == 9:
                """
                    Add some code for reduce 9 here...
                    T -> F
                """
                pass
            elif operation_number == 10:
                """
                    Add some code for reduce 10 here...
                    T -> T div F
                """
                pass
            elif operation_number == 11:
                """
                    Add some code for reduce 11 here...
                    T -> T times F
                """
                pass
            elif operation_number == 12:
                """
                    Add some code for reduce 12 here...
                    D -> N
                """
                pass
            else:
                raise Exception("Invalid reduce number: %d" % operation_number)
        elif operation_flag == "a":
            break
        else:
            raise Exception("Invalid action: %s" % operation)
    """
        Add some postprocessing code here...
    """
