"""
    Boson v0.1
    By: ict
    Email: ictxiangxin@gmail.com

    This code generated by boson python code generator.
    You need fill some reduce code to let it available.
"""


terminal_index = {
    "bl":    0,
    "plus":  1,
    "br":    2,
    "div":   3,
    "minus": 4,
    "power": 5,
    "float": 6,
    "int":   7,
    "times": 8,
    "$":     9,
}

action_table = [
    ["s6",  "e",   "e",   "e",   "e",   "e",   "s2",  "s7",  "e",     "e"],
    ["e",   "r9",  "r9",  "r9",  "r9",  "s9",  "e",   "e",   "r9",   "r9"],
    ["e",   "r7",  "r7",  "r7",  "r7",  "r7",  "e",   "e",   "r7",   "r7"],
    ["e",   "s10", "e",   "e",   "s11", "e",   "e",   "e",   "e",     "a"],
    ["e",   "r5",  "r5",  "r5",  "r5",  "r5",  "e",   "e",   "r5",   "r5"],
    ["e",   "r12", "r12", "r12", "r12", "r12", "e",   "e",   "r12", "r12"],
    ["s6",  "e",   "e",   "e",   "e",   "e",   "s2",  "s7",  "e",     "e"],
    ["e",   "r8",  "r8",  "r8",  "r8",  "r8",  "e",   "e",   "r8",   "r8"],
    ["e",   "r4",  "r4",  "s13", "r4",  "e",   "e",   "e",   "s14",  "r4"],
    ["s6",  "e",   "e",   "e",   "e",   "e",   "s2",  "s7",  "e",     "e"],
    ["s6",  "e",   "e",   "e",   "e",   "e",   "s2",  "s7",  "e",     "e"],
    ["s6",  "e",   "e",   "e",   "e",   "e",   "s2",  "s7",  "e",     "e"],
    ["e",   "s10", "s18", "e",   "s11", "e",   "e",   "e",   "e",     "e"],
    ["s6",  "e",   "e",   "e",   "e",   "e",   "s2",  "s7",  "e",     "e"],
    ["s6",  "e",   "e",   "e",   "e",   "e",   "s2",  "s7",  "e",     "e"],
    ["e",   "r6",  "r6",  "r6",  "r6",  "r6",  "e",   "e",   "r6",   "r6"],
    ["e",   "r3",  "r3",  "s13", "r3",  "e",   "e",   "e",   "s14",  "r3"],
    ["e",   "r2",  "r2",  "s13", "r2",  "e",   "e",   "e",   "s14",  "r2"],
    ["e",   "r1",  "r1",  "r1",  "r1",  "r1",  "e",   "e",   "r1",   "r1"],
    ["e",   "r10", "r10", "r10", "r10", "s9",  "e",   "e",   "r10", "r10"],
    ["e",   "r11", "r11", "r11", "r11", "s9",  "e",   "e",   "r11", "r11"],
]

non_terminal_index = {
    "N": 0,
    "E": 1,
    "D": 2,
    "F": 3,
    "T": 4,
}

goto_table = [
    [5,  3,  4,  1,   8],
    [-1, -1, -1, -1, -1],
    [-1, -1, -1, -1, -1],
    [-1, -1, -1, -1, -1],
    [-1, -1, -1, -1, -1],
    [-1, -1, -1, -1, -1],
    [5,  12, 4,  1,   8],
    [-1, -1, -1, -1, -1],
    [-1, -1, -1, -1, -1],
    [5,  -1, 15, -1, -1],
    [5,  -1, 4,  1,  16],
    [5,  -1, 4,  1,  17],
    [-1, -1, -1, -1, -1],
    [5,  -1, 4,  19, -1],
    [5,  -1, 4,  20, -1],
    [-1, -1, -1, -1, -1],
    [-1, -1, -1, -1, -1],
    [-1, -1, -1, -1, -1],
    [-1, -1, -1, -1, -1],
    [-1, -1, -1, -1, -1],
    [-1, -1, -1, -1, -1],
]

reduce_symbol_sum = {
    0:  1,
    1:  3,
    2:  3,
    3:  3,
    4:  1,
    5:  1,
    6:  3,
    7:  1,
    8:  1,
    9:  1,
    10: 3,
    11: 3,
    12: 1,
}

reduce_to_non_terminal = {
    0:  "start",
    1:  "D",
    2:  "E",
    3:  "E",
    4:  "E",
    5:  "F",
    6:  "F",
    7:  "N",
    8:  "N",
    9:  "T",
    10: "T",
    11: "T",
    12: "D",
}


def grammar_analysis(token_line):
    """
        Add some data structure definition code here...
    """
    stack = [0]
    token_index = 0
    while token_index < len(token_line):
        token = token_line[token_index]
        token_type = token[0]
        now_state = stack[-1]
        operation = action_table[now_state][terminal_index[token_type]]
        operation_flag = operation[0]
        if operation_flag == "e":
            raise Exception("Grammar error: " + " ".join([t[1] for t in token_line]))
        elif operation_flag == "s":
            operation_number = int(operation[1:])
            stack.append(operation_number)
            token_index += 1
            """
                Add some code for shift action here...
            """
        elif operation_flag == "r":
            operation_number = int(operation[1:])
            reduce_sum = reduce_symbol_sum[operation_number]
            for _ in range(reduce_sum):
                stack.pop()
            now_state = stack[-1]
            stack.append(goto_table[now_state][non_terminal_index[reduce_to_non_terminal[operation_number]]])
            if operation_number == 1:
                """
                    Add some code for reduce 1 here...
                    D -> bl E br
                """
                pass
            elif operation_number == 2:
                """
                    Add some code for reduce 2 here...
                    E -> E minus T
                """
                pass
            elif operation_number == 3:
                """
                    Add some code for reduce 3 here...
                    E -> E plus T
                """
                pass
            elif operation_number == 4:
                """
                    Add some code for reduce 4 here...
                    E -> T
                """
                pass
            elif operation_number == 5:
                """
                    Add some code for reduce 5 here...
                    F -> D
                """
                pass
            elif operation_number == 6:
                """
                    Add some code for reduce 6 here...
                    F -> F power D
                """
                pass
            elif operation_number == 7:
                """
                    Add some code for reduce 7 here...
                    N -> float
                """
                pass
            elif operation_number == 8:
                """
                    Add some code for reduce 8 here...
                    N -> int
                """
                pass
            elif operation_number == 9:
                """
                    Add some code for reduce 9 here...
                    T -> F
                """
                pass
            elif operation_number == 10:
                """
                    Add some code for reduce 10 here...
                    T -> T div F
                """
                pass
            elif operation_number == 11:
                """
                    Add some code for reduce 11 here...
                    T -> T times F
                """
                pass
            elif operation_number == 12:
                """
                    Add some code for reduce 12 here...
                    D -> N
                """
                pass
            else:
                raise Exception("Invalid reduce number: %d" % operation_number)
        elif operation_flag == "a":
            break
        else:
            raise Exception("Invalid action: %s" % operation)
    """
        Add some postprocessing code here...
    """
