"""
    Boson v0.1
    By: ict
    Email: ictxiangxin@gmail.com

    This code generated by boson SLR generator.
    You need fill some reduce code to let it available.
"""


terminal_index = {
    "div":   0,
    "int":   1,
    "minus": 2,
    "power": 3,
    "plus":  4,
    "br":    5,
    "bl":    6,
    "times": 7,
    "float": 8,
    "$":     9,
}

action_table = [
    ["e",   "s2",  "e",   "e",   "e",   "e",   "s3",  "e",   "s7",    "e"],
    ["s10", "e",   "r3",  "e",   "r3",  "r3",  "e",   "s9",  "e",    "r3"],
    ["r6",  "e",   "r6",  "r6",  "r6",  "r6",  "e",   "r6",  "e",    "r6"],
    ["e",   "s2",  "e",   "e",   "e",   "e",   "s3",  "e",   "s7",    "e"],
    ["r5",  "e",   "r5",  "r5",  "r5",  "r5",  "e",   "r5",  "e",    "r5"],
    ["r4",  "e",   "r4",  "s12", "r4",  "r4",  "e",   "r4",  "e",    "r4"],
    ["r8",  "e",   "r8",  "r8",  "r8",  "r8",  "e",   "r8",  "e",    "r8"],
    ["r7",  "e",   "r7",  "r7",  "r7",  "r7",  "e",   "r7",  "e",    "r7"],
    ["e",   "e",   "s13", "e",   "s14", "e",   "e",   "e",   "e",    "r9"],
    ["e",   "s2",  "e",   "e",   "e",   "e",   "s3",  "e",   "s7",    "e"],
    ["e",   "s2",  "e",   "e",   "e",   "e",   "s3",  "e",   "s7",    "e"],
    ["e",   "e",   "s13", "e",   "s14", "s17", "e",   "e",   "e",     "e"],
    ["e",   "s2",  "e",   "e",   "e",   "e",   "s3",  "e",   "s7",    "e"],
    ["e",   "s2",  "e",   "e",   "e",   "e",   "s3",  "e",   "s7",    "e"],
    ["e",   "s2",  "e",   "e",   "e",   "e",   "s3",  "e",   "s7",    "e"],
    ["r12", "e",   "r12", "s12", "r12", "r12", "e",   "r12", "e",   "r12"],
    ["r2",  "e",   "r2",  "s12", "r2",  "r2",  "e",   "r2",  "e",    "r2"],
    ["r1",  "e",   "r1",  "r1",  "r1",  "r1",  "e",   "r1",  "e",    "r1"],
    ["r0",  "e",   "r0",  "r0",  "r0",  "r0",  "e",   "r0",  "e",    "r0"],
    ["s10", "e",   "r10", "e",   "r10", "r10", "e",   "s9",  "e",   "r10"],
    ["s10", "e",   "r11", "e",   "r11", "r11", "e",   "s9",  "e",   "r11"],
]

non_terminal_index = {
    "D": 0,
    "T": 1,
    "N": 2,
    "F": 3,
    "E": 4,
}

goto_table = [
    [6,  1,  4,  5,   5],
    [-1, -1, -1, -1, -1],
    [-1, -1, -1, -1, -1],
    [6,  1,  4,  5,   5],
    [-1, -1, -1, -1, -1],
    [-1, -1, -1, -1, -1],
    [-1, -1, -1, -1, -1],
    [-1, -1, -1, -1, -1],
    [-1, -1, -1, -1, -1],
    [6,  -1, 4,  15, 15],
    [6,  -1, 4,  16, 16],
    [-1, -1, -1, -1, -1],
    [18, -1, 4,  -1, -1],
    [6,  19, 4,  5,   5],
    [6,  20, 4,  5,   5],
    [-1, -1, -1, -1, -1],
    [-1, -1, -1, -1, -1],
    [-1, -1, -1, -1, -1],
    [-1, -1, -1, -1, -1],
    [-1, -1, -1, -1, -1],
    [-1, -1, -1, -1, -1],
]

reduce_symbol_sum = {
    0:  3,
    1:  3,
    2:  3,
    3:  1,
    4:  1,
    5:  1,
    6:  1,
    7:  1,
    8:  1,
    9:  1,
    10: 3,
    11: 3,
    12: 3,
}

reduce_to_non_terminal = {
    0:  "F",
    1:  "D",
    2:  "T",
    3:  "E",
    4:  "T",
    5:  "D",
    6:  "N",
    7:  "N",
    8:  "F",
    9:  "start",
    10: "E",
    11: "E",
    12: "T",
}


def grammar_analysis(token_line):
    """
        Add some data structure definition code here...
    """
    stack = [0]
    token_index = 0
    while token_index < len(token_line):
        token = token_line[token_index]
        token_type = token[0]
        now_state = stack[-1]
        operation = action_table[now_state][terminal_index[token_type]]
        operation_flag = operation[0]
        if operation_flag == "e":
            raise Exception("Grammar error: " + " ".join([t[1] for t in token_line]))
        elif operation_flag == "s":
            operation_number = int(operation[1:])
            stack.append(operation_number)
            token_index += 1
            """
                Add some code for shift action here...
            """
        elif operation_flag == "r":
            operation_number = int(operation[1:])
            reduce_sum = reduce_symbol_sum[operation_number]
            for _ in range(reduce_sum):
                stack.pop()
            now_state = stack[-1]
            stack.append(goto_table[now_state][non_terminal_index[reduce_to_non_terminal[operation_number]]])
            if operation_number == 0:
                """
                    Add some code for reduce 0 here...
                    F -> F power D
                """
                pass
            elif operation_number == 1:
                """
                    Add some code for reduce 1 here...
                    D -> bl E br
                """
                pass
            elif operation_number == 2:
                """
                    Add some code for reduce 2 here...
                    T -> T div F
                """
                pass
            elif operation_number == 3:
                """
                    Add some code for reduce 3 here...
                    E -> T
                """
                pass
            elif operation_number == 4:
                """
                    Add some code for reduce 4 here...
                    T -> F
                """
                pass
            elif operation_number == 5:
                """
                    Add some code for reduce 5 here...
                    D -> N
                """
                pass
            elif operation_number == 6:
                """
                    Add some code for reduce 6 here...
                    N -> int
                """
                pass
            elif operation_number == 7:
                """
                    Add some code for reduce 7 here...
                    N -> float
                """
                pass
            elif operation_number == 8:
                """
                    Add some code for reduce 8 here...
                    F -> D
                """
                pass
            elif operation_number == 9:
                """
                    Add some code for reduce 9 here...
                    start -> E
                """
                pass
            elif operation_number == 10:
                """
                    Add some code for reduce 10 here...
                    E -> E minus T
                """
                pass
            elif operation_number == 11:
                """
                    Add some code for reduce 11 here...
                    E -> E plus T
                """
                pass
            elif operation_number == 12:
                """
                    Add some code for reduce 12 here...
                    T -> T times F
                """
                pass
            else:
                raise Exception("Invalid reduce number: %d" % operation_number)
        elif operation_flag == "a":
            break
        else:
            raise Exception("Invalid action: %s" % operation)
    """
        Add some postprocessing code here...
    """
