language: python
python:
    - "3.3"
    - "3.4"
    - "3.5"
install:
    - python3 setup.py install
script:
    - python3 test/test.py
notifications:
    email:
        on_success: never
        on_failure: always