"""
    Boson v0.8 - Grammar analyzer generator

        Author: ict
        Email:  ictxiangxin@hotmail.com
        Site:   https://github.com/ictxiangxin/boson

    This code was generated by boson python code generator.

         0: !name_0 -> !name_0 statement
         1: !name_0 -> statement
         2: !name_1 -> !name_1 argument
         3: !name_1 -> argument
         4: !name_10 -> !name_10 !name_9
         5: !name_10 -> ~
         6: !name_11 -> star
         7: !name_12 -> !name_11
         8: !name_12 -> ~
         9: !name_13 -> grammar_tuple
        10: !name_14 -> !name_13
        11: !name_14 -> ~
        12: !name_15 -> closure
        13: !name_16 -> !name_15
        14: !name_16 -> ~
        15: !name_17 -> !name_17 element
        16: !name_17 -> element
        17: !name_18 -> closure
        18: !name_19 -> !name_18
        19: !name_19 -> ~
        20: !name_2 -> or derivation
        21: !name_20 -> !name_20 element
        22: !name_20 -> element
        23: !name_3 -> !name_3 !name_2
        24: !name_3 -> ~
        25: !name_4 -> name
        26: !name_5 -> !name_4
        27: !name_5 -> ~
        28: !name_6 -> assign !name_5 grammar_tuple
        29: !name_7 -> !name_6
        30: !name_7 -> ~
        31: !name_8 -> !name_8 element
        32: !name_8 -> element
        33: !name_9 -> comma node_element
        34: argument -> literal
        35: argument -> name
        36: closure -> plus
        37: closure -> star
        38: command_statement -> command !name_1 end
        39: complex_element -> bracket_l !name_20 bracket_r
        40: complex_element -> parentheses_l !name_17 parentheses_r !name_19
        41: derivation -> derivation_body !name_7
        42: derivation_body -> !name_8
        43: derivation_body -> null
        44: derivation_body -> ~
        45: derivation_list -> derivation !name_3
        46: element -> complex_element
        47: element -> literal
        48: element -> name !name_16
        49: grammar -> !name_0
        50: grammar_tuple -> parentheses_l node_list parentheses_r
        51: node_element -> !name_12 node !name_14
        52: node_list -> node_element !name_10
        53: reduction_statement -> name reduce derivation_list end
        54: statement -> command_statement
        55: statement -> reduction_statement
"""


class BosonGrammar:
    def __init__(self):
        self.__grammar_tree = None
        self.__error_index = None

    def get_grammar_tree(self):
        return self.__grammar_tree

    def set_grammar_tree(self, grammar_tree: tuple):
        self.__grammar_tree = grammar_tree

    grammar_tree = property(get_grammar_tree, set_grammar_tree)

    def get_error_index(self):
        return self.__error_index

    def set_error_index(self, error_index: int):
        self.__error_index = error_index

    error_index = property(get_error_index, set_error_index)


class BosonGrammarNode:
    def __init__(self):
        self.reduce_number = -1
        self.__data = []

    def __getitem__(self, item):
        return self.__data[item]

    def __iadd__(self, other):
        self.__data += other
        return self

    def append(self, item):
        self.__data.append(item)

    def insert(self, index, item):
        self.__data.insert(index, item)

    def data(self):
        return self.__data


class BosonEBNFAnalyzer:
    def __init__(self):
        self.__terminal_index = {
            'assign': 0,
            '$': 1,
            'name': 2,
            'end': 3,
            'or': 4,
            'star': 5,
            'bracket_l': 6,
            'parentheses_r': 7,
            'command': 8,
            'plus': 9,
            'comma': 10,
            'bracket_r': 11,
            'parentheses_l': 12,
            'node': 13,
            'null': 14,
            'reduce': 15,
            'literal': 16
        }
        self.__action_table = {
            0: {2: 's3', 8: 's7'},
            1: {1: 'r2', 2: 'r2', 8: 'r2'},
            2: {1: 'r50', 2: 's3', 8: 's7'},
            3: {15: 's9'},
            4: {1: 'a'},
            5: {1: 'r55', 2: 'r55', 8: 'r55'},
            6: {1: 'r56', 2: 'r56', 8: 'r56'},
            7: {2: 's13', 16: 's11'},
            8: {1: 'r1', 2: 'r1', 8: 'r1'},
            9: {0: 'r45', 2: 's17', 3: 'r45', 4: 'r45', 6: 's19', 12: 's24', 14: 's15', 16: 's21'},
            10: {2: 's13', 3: 's25', 16: 's11'},
            11: {2: 'r35', 3: 'r35', 16: 'r35'},
            12: {2: 'r4', 3: 'r4', 16: 'r4'},
            13: {2: 'r36', 3: 'r36', 16: 'r36'},
            14: {0: 'r47', 2: 'r47', 3: 'r47', 4: 'r47', 6: 'r47', 7: 'r47', 11: 'r47', 12: 'r47', 16: 'r47'},
            15: {0: 'r44', 3: 'r44', 4: 'r44'},
            16: {0: 'r43', 2: 's17', 3: 'r43', 4: 'r43', 6: 's19', 12: 's24', 16: 's21'},
            17: {0: 'r15', 2: 'r15', 3: 'r15', 4: 'r15', 5: 's29', 6: 'r15', 7: 'r15', 9: 's28', 11: 'r15', 12: 'r15', 16: 'r15'},
            18: {3: 'r25', 4: 'r25'},
            19: {2: 's17', 6: 's19', 12: 's24', 16: 's21'},
            20: {3: 's36'},
            21: {0: 'r48', 2: 'r48', 3: 'r48', 4: 'r48', 6: 'r48', 7: 'r48', 11: 'r48', 12: 'r48', 16: 'r48'},
            22: {0: 's38', 3: 'r31', 4: 'r31'},
            23: {0: 'r33', 2: 'r33', 3: 'r33', 4: 'r33', 6: 'r33', 12: 'r33', 16: 'r33'},
            24: {2: 's17', 6: 's19', 12: 's24', 16: 's21'},
            25: {1: 'r39', 2: 'r39', 8: 'r39'},
            26: {2: 'r3', 3: 'r3', 16: 'r3'},
            27: {0: 'r32', 2: 'r32', 3: 'r32', 4: 'r32', 6: 'r32', 12: 'r32', 16: 'r32'},
            28: {0: 'r37', 2: 'r37', 3: 'r37', 4: 'r37', 6: 'r37', 7: 'r37', 11: 'r37', 12: 'r37', 16: 'r37'},
            29: {0: 'r38', 2: 'r38', 3: 'r38', 4: 'r38', 6: 'r38', 7: 'r38', 11: 'r38', 12: 'r38', 16: 'r38'},
            30: {0: 'r49', 2: 'r49', 3: 'r49', 4: 'r49', 6: 'r49', 7: 'r49', 11: 'r49', 12: 'r49', 16: 'r49'},
            31: {0: 'r14', 2: 'r14', 3: 'r14', 4: 'r14', 6: 'r14', 7: 'r14', 11: 'r14', 12: 'r14', 16: 'r14'},
            32: {0: 'r13', 2: 'r13', 3: 'r13', 4: 'r13', 6: 'r13', 7: 'r13', 11: 'r13', 12: 'r13', 16: 'r13'},
            33: {3: 'r46', 4: 's43'},
            34: {2: 'r23', 6: 'r23', 11: 'r23', 12: 'r23', 16: 'r23'},
            35: {2: 's17', 6: 's19', 11: 's44', 12: 's24', 16: 's21'},
            36: {1: 'r54', 2: 'r54', 8: 'r54'},
            37: {3: 'r42', 4: 'r42'},
            38: {2: 's46', 12: 'r28'},
            39: {3: 'r30', 4: 'r30'},
            40: {2: 'r17', 6: 'r17', 7: 'r17', 12: 'r17', 16: 'r17'},
            41: {2: 's17', 6: 's19', 7: 's49', 12: 's24', 16: 's21'},
            42: {3: 'r24', 4: 'r24'},
            43: {0: 'r45', 2: 's17', 3: 'r45', 4: 'r45', 6: 's19', 12: 's24', 14: 's15', 16: 's21'},
            44: {0: 'r40', 2: 'r40', 3: 'r40', 4: 'r40', 6: 'r40', 7: 'r40', 11: 'r40', 12: 'r40', 16: 'r40'},
            45: {2: 'r22', 6: 'r22', 11: 'r22', 12: 'r22', 16: 'r22'},
            46: {12: 'r26'},
            47: {12: 's52'},
            48: {12: 'r27'},
            49: {0: 'r20', 2: 'r20', 3: 'r20', 4: 'r20', 5: 's29', 6: 'r20', 7: 'r20', 9: 's28', 11: 'r20', 12: 'r20', 16: 'r20'},
            50: {2: 'r16', 6: 'r16', 7: 'r16', 12: 'r16', 16: 'r16'},
            51: {3: 'r21', 4: 'r21'},
            52: {5: 's59', 13: 'r9'},
            53: {3: 'r29', 4: 'r29'},
            54: {0: 'r19', 2: 'r19', 3: 'r19', 4: 'r19', 6: 'r19', 7: 'r19', 11: 'r19', 12: 'r19', 16: 'r19'},
            55: {0: 'r41', 2: 'r41', 3: 'r41', 4: 'r41', 6: 'r41', 7: 'r41', 11: 'r41', 12: 'r41', 16: 'r41'},
            56: {0: 'r18', 2: 'r18', 3: 'r18', 4: 'r18', 6: 'r18', 7: 'r18', 11: 'r18', 12: 'r18', 16: 'r18'},
            57: {13: 's62'},
            58: {7: 'r6', 10: 'r6'},
            59: {13: 'r7'},
            60: {7: 's64'},
            61: {13: 'r8'},
            62: {7: 'r12', 10: 'r12', 12: 's52'},
            63: {7: 'r53', 10: 's69'},
            64: {3: 'r51', 4: 'r51', 7: 'r51', 10: 'r51'},
            65: {7: 'r11', 10: 'r11'},
            66: {7: 'r52', 10: 'r52'},
            67: {7: 'r10', 10: 'r10'},
            68: {7: 'r5', 10: 'r5'},
            69: {5: 's59', 13: 'r9'},
            70: {7: 'r34', 10: 'r34'}
        }
        self.__goto_table = {
            0: {6: 4, 15: 6, 18: 5, 25: 1, 34: 2},
            2: {15: 6, 18: 5, 25: 8},
            7: {9: 12, 33: 10},
            9: {0: 14, 14: 18, 16: 23, 23: 20, 28: 16, 29: 22},
            10: {9: 26},
            16: {0: 14, 16: 27},
            17: {4: 31, 17: 32, 27: 30},
            18: {13: 33},
            19: {0: 14, 1: 35, 16: 34},
            22: {2: 39, 22: 37},
            24: {0: 14, 12: 41, 16: 40},
            33: {8: 42},
            35: {0: 14, 16: 45},
            38: {21: 47, 35: 48},
            41: {0: 14, 16: 50},
            43: {0: 14, 14: 51, 16: 23, 28: 16, 29: 22},
            47: {5: 53},
            49: {17: 56, 19: 55, 32: 54},
            52: {3: 58, 20: 61, 24: 60, 26: 57},
            58: {30: 63},
            62: {5: 67, 7: 66, 31: 65},
            63: {11: 68},
            69: {3: 70, 20: 61, 26: 57}
        }
        self.__node_table = {
            0: ('*0', '1'),
            1: ('0',),
            49: ('*0',),
            2: ('*0', '1'),
            3: ('0',),
            38: ('0', '*1'),
            53: ('0', '2'),
            20: ('?',),
            23: ('*0', '1'),
            24: (),
            45: ('0', ('*1', ('1',))),
            25: ('?',),
            26: ('0',),
            27: (),
            28: ('?',),
            29: ('0',),
            30: (),
            41: ('0', ('*1', (('*1', ('?',)), '2'))),
            31: ('*0', '1'),
            32: ('0',),
            42: ('*0',),
            50: ('*1',),
            33: ('?',),
            4: ('*0', '1'),
            5: (),
            52: ('0', ('*1', ('1',))),
            6: ('?',),
            7: ('0',),
            8: (),
            9: ('?',),
            10: ('0',),
            11: (),
            51: (('*0', ('?',)), '1', ('*2', ('?',))),
            12: ('?',),
            13: ('0',),
            14: (),
            48: ('0', ('*1', ('?',))),
            47: ('0',),
            15: ('*0', '1'),
            16: ('0',),
            17: ('?',),
            18: ('0',),
            19: (),
            21: ('*0', '1'),
            22: ('0',),
            40: ('*1', ('*3', ('?',))),
            39: ('*1',)
        }
        self.__reduce_symbol_sum = [2, 1, 2, 1, 2, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 2, 1, 1, 1, 0, 2, 2, 1, 2, 0, 1, 1, 0, 3, 1, 0, 2, 1, 2, 1, 1, 1, 1, 3, 3, 4, 2, 1, 1, 0, 2, 1, 1, 2, 1, 3, 3, 2, 4, 1, 1]
        self.__reduce_to_non_terminal_index = [34, 34, 33, 33, 30, 30, 20, 26, 26, 31, 7, 7, 4, 27, 27, 12, 12, 32, 19, 19, 8, 1, 1, 13, 13, 35, 21, 21, 2, 22, 22, 28, 28, 11, 9, 9, 17, 17, 18, 0, 0, 14, 29, 29, 29, 23, 16, 16, 16, 6, 5, 3, 24, 15, 25, 25]

    def __generate_grammar_tuple(self, statement_index, symbol_package):
        grammar_node = BosonGrammarNode()
        if isinstance(statement_index, int):
            node_tuple = self.__node_table[statement_index]
        else:
            node_tuple = statement_index
            statement_index = -1
        for i in node_tuple:
            if isinstance(i, str):
                if i == '$':
                    grammar_node.append(statement_index)
                elif i == '?':
                    grammar_node += symbol_package
                else:
                    if symbol_package:
                        if i[0] == '*':
                            grammar_node += symbol_package[int(i[1:])]
                        else:
                            grammar_node.append(symbol_package[int(i)])
            else:
                if symbol_package:
                    if i[0][0] == '*':
                        for node in symbol_package[int(i[0][1:])]:
                            grammar_node += self.__generate_grammar_tuple(i[1], node)
                    else:
                        for node in symbol_package[int(i[0])]:
                            grammar_node.append(self.__generate_grammar_tuple(i[1], node))
        grammar_node.reduce_number = statement_index
        return grammar_node

    def grammar_analysis(self, token_list):
        grammar = BosonGrammar()
        analysis_stack = [0]
        symbol_stack = []
        token_index = 0
        while token_index < len(token_list):
            token = token_list[token_index]
            current_state = analysis_stack[-1]
            operation = self.__action_table.get(current_state, {}).get(self.__terminal_index[token.symbol], 'e')
            operation_flag = operation[0]
            if operation_flag == 'e':
                grammar.error_index = token_index
                return grammar
            elif operation_flag == 's':
                state_number = int(operation[1:])
                analysis_stack.append(state_number)
                token_index += 1
                symbol_stack.append(token.text)
            elif operation_flag == 'r':
                statement_index = int(operation[1:]) - 1
                reduce_sum = self.__reduce_symbol_sum[statement_index]
                for _ in range(reduce_sum):
                    analysis_stack.pop()
                current_state = analysis_stack[-1]
                current_non_terminal_index = self.__reduce_to_non_terminal_index[statement_index]
                goto_next_state = self.__goto_table.get(current_state, {}).get(current_non_terminal_index, -1)
                if goto_next_state == -1:
                    raise ValueError('Invalid goto action: state={}, non-terminal={}'.format(current_state, current_non_terminal_index))
                analysis_stack.append(goto_next_state)
                if statement_index in self.__node_table:
                    symbol_package = []
                    for _ in range(reduce_sum):
                        symbol_package.insert(0, symbol_stack.pop())
                    symbol_stack.append(self.__generate_grammar_tuple(statement_index, symbol_package))
                elif statement_index in [34, 35, 36, 37, 43, 44, 46, 54, 55]:
                    grammar_node = BosonGrammarNode()
                    for _ in range(reduce_sum):
                        grammar_node.insert(0, symbol_stack.pop())
                    grammar_node.reduce_number = statement_index
                    symbol_stack.append(grammar_node)
                else:
                    raise ValueError('Invalid reduce number: reduce={}'.format(statement_index))
            elif operation_flag == 'a':
                grammar.grammar_tree = symbol_stack[0]
                return grammar
            else:
                raise ValueError('Invalid action: action={}'.format(operation))
        raise RuntimeError('Analyzer unusual exit.')


class BosonSemanticAnalyzer:
    def __init__(self):
        self.__reduce_number_to_grammar_name = {
            38: 'command',
            53: 'reduce',
            51: 'grammar_node',
            48: 'name_closure',
            47: 'literal',
            40: 'complex_closure',
            39: 'complex_optional'
        }
        self.__reduce_number_to_grammar_number = {
            49: 0,
            54: 1,
            55: 2,
            35: 4,
            34: 5,
            45: 7,
            41: 8,
            42: 9,
            43: 10,
            44: 11,
            50: 12,
            52: 13,
            46: 15,
            36: 20,
            37: 21
        }
        self.__naive_reduce_number = {34, 35, 36, 37, 42, 43, 44, 46, 47, 49, 54, 55}
        self.__semantic_entity = {}

    @staticmethod
    def __default_semantic_entity(grammar_entity):
        return grammar_entity

    @staticmethod
    def __naive_semantic_entity(grammar_entity):
        if len(grammar_entity) == 0:
            return None
        elif len(grammar_entity) == 1:
            return grammar_entity[0]
        else:
            return grammar_entity

    def __semantic_analysis(self, grammar_tree: BosonGrammarNode):
        if grammar_tree.reduce_number in self.__reduce_number_to_grammar_name:
            grammar_name = self.__reduce_number_to_grammar_name[grammar_tree.reduce_number]
        elif grammar_tree.reduce_number in self.__reduce_number_to_grammar_number:
            grammar_name = '!grammar_{}'.format(self.__reduce_number_to_grammar_number[grammar_tree.reduce_number])
        else:
            grammar_name = '!grammar_{}'.format('hidden')
        grammar_entity = list(map(lambda g: self.__semantic_analysis(g) if isinstance(g, BosonGrammarNode) else g, grammar_tree.data()))
        if grammar_name in self.__semantic_entity:
            return self.__semantic_entity[grammar_name](grammar_entity)
        if grammar_tree.reduce_number in self.__naive_reduce_number:
            return self.__naive_semantic_entity(grammar_entity)
        else:
            return self.__default_semantic_entity(grammar_entity)

    def semantic_analysis(self, grammar_tree: BosonGrammarNode):
        return self.__semantic_analysis(grammar_tree)

    def semantic_entity(self, sign):
        def decorator(f):
            if isinstance(sign, int):
                name = '!grammar_{}'.format(sign)
            elif isinstance(sign, str):
                name = sign
            else:
                raise ValueError('Invalid grammar sign: {}'.format(sign))
            self.__semantic_entity[name] = f
            return f
        return decorator
