"""
    Boson v0.8 - Grammar analyzer generator

        Author: ict
        Email:  ictxiangxin@hotmail.com
        Site:   https://github.com/ictxiangxin/boson

    This code was generated by boson python code generator.

         0: !name_0 -> !name_0 statement
         1: !name_0 -> statement
         2: !name_1 -> !name_1 argument
         3: !name_1 -> argument
         4: !name_10 -> !name_10 !name_9
         5: !name_10 -> ~
         6: !name_11 -> star
         7: !name_12 -> !name_11
         8: !name_12 -> ~
         9: !name_13 -> grammar_tuple
        10: !name_14 -> !name_13
        11: !name_14 -> ~
        12: !name_15 -> closure
        13: !name_16 -> !name_15
        14: !name_16 -> ~
        15: !name_17 -> !name_17 element
        16: !name_17 -> element
        17: !name_18 -> closure
        18: !name_19 -> !name_18
        19: !name_19 -> ~
        20: !name_2 -> or derivation
        21: !name_20 -> !name_20 element
        22: !name_20 -> element
        23: !name_3 -> !name_3 !name_2
        24: !name_3 -> ~
        25: !name_4 -> name
        26: !name_5 -> !name_4
        27: !name_5 -> ~
        28: !name_6 -> assign !name_5 grammar_tuple
        29: !name_7 -> !name_6
        30: !name_7 -> ~
        31: !name_8 -> !name_8 element
        32: !name_8 -> element
        33: !name_9 -> comma node_element
        34: argument -> literal
        35: argument -> name
        36: closure -> plus
        37: closure -> star
        38: command_statement -> command !name_1 end
        39: complex_element -> bracket_l !name_20 bracket_r
        40: complex_element -> parentheses_l !name_17 parentheses_r !name_19
        41: derivation -> derivation_body !name_7
        42: derivation_body -> !name_8
        43: derivation_body -> null
        44: derivation_body -> ~
        45: derivation_list -> derivation !name_3
        46: element -> complex_element
        47: element -> literal
        48: element -> name !name_16
        49: grammar -> !name_0
        50: grammar_tuple -> parentheses_l node_list parentheses_r
        51: node_element -> !name_12 node !name_14
        52: node_list -> node_element !name_10
        53: reduction_statement -> name reduce derivation_list end
        54: statement -> command_statement
        55: statement -> reduction_statement
"""


class BosonGrammar:
    def __init__(self):
        self.__grammar_tree = None
        self.__error_index = None

    def get_grammar_tree(self):
        return self.__grammar_tree

    def set_grammar_tree(self, grammar_tree: tuple):
        self.__grammar_tree = grammar_tree

    grammar_tree = property(get_grammar_tree, set_grammar_tree)

    def get_error_index(self):
        return self.__error_index

    def set_error_index(self, error_index: int):
        self.__error_index = error_index

    error_index = property(get_error_index, set_error_index)


class BosonGrammarNode:
    def __init__(self):
        self.reduce_number = -1
        self.__data = []

    def __getitem__(self, item):
        return self.__data[item]

    def __iadd__(self, other):
        self.__data += other
        return self

    def append(self, item):
        self.__data.append(item)

    def insert(self, index, item):
        self.__data.insert(index, item)

    def data(self):
        return self.__data


class BosonEBNFAnalyzer:
    def __init__(self):
        self.__terminal_index = {
            'reduce': 0,
            'parentheses_r': 1,
            'bracket_r': 2,
            'star': 3,
            'name': 4,
            'comma': 5,
            'plus': 6,
            'assign': 7,
            'node': 8,
            'command': 9,
            'bracket_l': 10,
            'or': 11,
            'literal': 12,
            '$': 13,
            'null': 14,
            'end': 15,
            'parentheses_l': 16
        }
        self.__action_table = {
            0: {4: 's4', 9: 's2'},
            1: {4: 'r55', 9: 'r55', 13: 'r55'},
            2: {4: 's8', 12: 's10'},
            3: {4: 's4', 9: 's2', 13: 'r50'},
            4: {0: 's13'},
            5: {4: 'r56', 9: 'r56', 13: 'r56'},
            6: {13: 'a'},
            7: {4: 'r2', 9: 'r2', 13: 'r2'},
            8: {4: 'r36', 12: 'r36', 15: 'r36'},
            9: {4: 's8', 12: 's10', 15: 's15'},
            10: {4: 'r35', 12: 'r35', 15: 'r35'},
            11: {4: 'r4', 12: 'r4', 15: 'r4'},
            12: {4: 'r1', 9: 'r1', 13: 'r1'},
            13: {4: 's17', 7: 'r45', 10: 's16', 11: 'r45', 12: 's25', 14: 's23', 15: 'r45', 16: 's22'},
            14: {4: 'r3', 12: 'r3', 15: 'r3'},
            15: {4: 'r39', 9: 'r39', 13: 'r39'},
            16: {4: 's17', 10: 's16', 12: 's25', 16: 's22'},
            17: {1: 'r15', 2: 'r15', 3: 's33', 4: 'r15', 6: 's29', 7: 'r15', 10: 'r15', 11: 'r15', 12: 'r15', 15: 'r15', 16: 'r15'},
            18: {4: 'r33', 7: 'r33', 10: 'r33', 11: 'r33', 12: 'r33', 15: 'r33', 16: 'r33'},
            19: {11: 'r25', 15: 'r25'},
            20: {1: 'r47', 2: 'r47', 4: 'r47', 7: 'r47', 10: 'r47', 11: 'r47', 12: 'r47', 15: 'r47', 16: 'r47'},
            21: {4: 's17', 7: 'r43', 10: 's16', 11: 'r43', 12: 's25', 15: 'r43', 16: 's22'},
            22: {4: 's17', 10: 's16', 12: 's25', 16: 's22'},
            23: {7: 'r44', 11: 'r44', 15: 'r44'},
            24: {15: 's38'},
            25: {1: 'r48', 2: 'r48', 4: 'r48', 7: 'r48', 10: 'r48', 11: 'r48', 12: 'r48', 15: 'r48', 16: 'r48'},
            26: {7: 's39', 11: 'r31', 15: 'r31'},
            27: {2: 'r23', 4: 'r23', 10: 'r23', 12: 'r23', 16: 'r23'},
            28: {2: 's42', 4: 's17', 10: 's16', 12: 's25', 16: 's22'},
            29: {1: 'r37', 2: 'r37', 4: 'r37', 7: 'r37', 10: 'r37', 11: 'r37', 12: 'r37', 15: 'r37', 16: 'r37'},
            30: {1: 'r49', 2: 'r49', 4: 'r49', 7: 'r49', 10: 'r49', 11: 'r49', 12: 'r49', 15: 'r49', 16: 'r49'},
            31: {1: 'r14', 2: 'r14', 4: 'r14', 7: 'r14', 10: 'r14', 11: 'r14', 12: 'r14', 15: 'r14', 16: 'r14'},
            32: {1: 'r13', 2: 'r13', 4: 'r13', 7: 'r13', 10: 'r13', 11: 'r13', 12: 'r13', 15: 'r13', 16: 'r13'},
            33: {1: 'r38', 2: 'r38', 4: 'r38', 7: 'r38', 10: 'r38', 11: 'r38', 12: 'r38', 15: 'r38', 16: 'r38'},
            34: {11: 's45', 15: 'r46'},
            35: {4: 'r32', 7: 'r32', 10: 'r32', 11: 'r32', 12: 'r32', 15: 'r32', 16: 'r32'},
            36: {1: 'r17', 4: 'r17', 10: 'r17', 12: 'r17', 16: 'r17'},
            37: {1: 's46', 4: 's17', 10: 's16', 12: 's25', 16: 's22'},
            38: {4: 'r54', 9: 'r54', 13: 'r54'},
            39: {4: 's48', 16: 'r28'},
            40: {11: 'r30', 15: 'r30'},
            41: {11: 'r42', 15: 'r42'},
            42: {1: 'r40', 2: 'r40', 4: 'r40', 7: 'r40', 10: 'r40', 11: 'r40', 12: 'r40', 15: 'r40', 16: 'r40'},
            43: {2: 'r22', 4: 'r22', 10: 'r22', 12: 'r22', 16: 'r22'},
            44: {11: 'r24', 15: 'r24'},
            45: {4: 's17', 7: 'r45', 10: 's16', 11: 'r45', 12: 's25', 14: 's23', 15: 'r45', 16: 's22'},
            46: {1: 'r20', 2: 'r20', 3: 's33', 4: 'r20', 6: 's29', 7: 'r20', 10: 'r20', 11: 'r20', 12: 'r20', 15: 'r20', 16: 'r20'},
            47: {1: 'r16', 4: 'r16', 10: 'r16', 12: 'r16', 16: 'r16'},
            48: {16: 'r26'},
            49: {16: 's55'},
            50: {16: 'r27'},
            51: {11: 'r21', 15: 'r21'},
            52: {1: 'r19', 2: 'r19', 4: 'r19', 7: 'r19', 10: 'r19', 11: 'r19', 12: 'r19', 15: 'r19', 16: 'r19'},
            53: {1: 'r18', 2: 'r18', 4: 'r18', 7: 'r18', 10: 'r18', 11: 'r18', 12: 'r18', 15: 'r18', 16: 'r18'},
            54: {1: 'r41', 2: 'r41', 4: 'r41', 7: 'r41', 10: 'r41', 11: 'r41', 12: 'r41', 15: 'r41', 16: 'r41'},
            55: {3: 's57', 8: 'r9'},
            56: {11: 'r29', 15: 'r29'},
            57: {8: 'r7'},
            58: {1: 'r6', 5: 'r6'},
            59: {8: 'r8'},
            60: {8: 's63'},
            61: {1: 's64'},
            62: {1: 'r53', 5: 's65'},
            63: {1: 'r12', 5: 'r12', 16: 's55'},
            64: {1: 'r51', 5: 'r51', 11: 'r51', 15: 'r51'},
            65: {3: 's57', 8: 'r9'},
            66: {1: 'r5', 5: 'r5'},
            67: {1: 'r11', 5: 'r11'},
            68: {1: 'r10', 5: 'r10'},
            69: {1: 'r52', 5: 'r52'},
            70: {1: 'r34', 5: 'r34'}
        }
        self.__goto_table = {
            0: {2: 6, 10: 7, 15: 1, 32: 3, 35: 5},
            2: {4: 9, 29: 11},
            3: {10: 12, 15: 1, 35: 5},
            9: {29: 14},
            13: {0: 19, 9: 20, 12: 26, 14: 21, 17: 18, 34: 24},
            16: {9: 20, 17: 27, 28: 28},
            17: {8: 30, 24: 31, 26: 32},
            19: {21: 34},
            21: {9: 20, 17: 35},
            22: {9: 20, 17: 36, 19: 37},
            26: {3: 41, 30: 40},
            28: {9: 20, 17: 43},
            34: {7: 44},
            37: {9: 20, 17: 47},
            39: {1: 50, 22: 49},
            45: {0: 51, 9: 20, 12: 26, 14: 21, 17: 18},
            46: {25: 54, 26: 53, 33: 52},
            49: {18: 56},
            55: {13: 60, 16: 58, 23: 61, 27: 59},
            58: {20: 62},
            62: {31: 66},
            63: {5: 67, 6: 69, 18: 68},
            65: {13: 60, 16: 70, 27: 59}
        }
        self.__node_table = {
            0: ('*0', '1'),
            1: ('0',),
            49: ('*0',),
            2: ('*0', '1'),
            3: ('0',),
            38: ('0', '*1'),
            53: ('0', '2'),
            20: ('?',),
            23: ('*0', '1'),
            24: (),
            45: ('0', ('*1', ('1',))),
            25: ('?',),
            26: ('0',),
            27: (),
            28: ('?',),
            29: ('0',),
            30: (),
            41: ('0', ('*1', (('*1', ('?',)), '2'))),
            31: ('*0', '1'),
            32: ('0',),
            42: ('*0',),
            50: ('*1',),
            33: ('?',),
            4: ('*0', '1'),
            5: (),
            52: ('0', ('*1', ('1',))),
            6: ('?',),
            7: ('0',),
            8: (),
            9: ('?',),
            10: ('0',),
            11: (),
            51: (('*0', ('?',)), '1', ('*2', ('?',))),
            12: ('?',),
            13: ('0',),
            14: (),
            48: ('0', ('*1', ('?',))),
            47: ('0',),
            15: ('*0', '1'),
            16: ('0',),
            17: ('?',),
            18: ('0',),
            19: (),
            21: ('*0', '1'),
            22: ('0',),
            40: ('*1', ('*3', ('?',))),
            39: ('*1',)
        }
        self.__reduce_symbol_sum = [2, 1, 2, 1, 2, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 2, 1, 1, 1, 0, 2, 2, 1, 2, 0, 1, 1, 0, 3, 1, 0, 2, 1, 2, 1, 1, 1, 1, 3, 3, 4, 2, 1, 1, 0, 2, 1, 1, 2, 1, 3, 3, 2, 4, 1, 1]
        self.__reduce_to_non_terminal_index = [32, 32, 4, 4, 20, 20, 27, 13, 13, 5, 6, 6, 24, 8, 8, 19, 19, 33, 25, 25, 7, 28, 28, 21, 21, 1, 22, 22, 30, 3, 3, 14, 14, 31, 29, 29, 26, 26, 15, 9, 9, 0, 12, 12, 12, 34, 17, 17, 17, 2, 18, 16, 23, 35, 10, 10]

    def __generate_grammar_tuple(self, statement_index, symbol_package):
        grammar_node = BosonGrammarNode()
        if isinstance(statement_index, int):
            node_tuple = self.__node_table[statement_index]
        else:
            node_tuple = statement_index
            statement_index = -1
        for i in node_tuple:
            if isinstance(i, str):
                if i == '$':
                    grammar_node.append(statement_index)
                elif i == '?':
                    grammar_node += symbol_package
                else:
                    if symbol_package:
                        if i[0] == '*':
                            grammar_node += symbol_package[int(i[1:])]
                        else:
                            grammar_node.append(symbol_package[int(i)])
            else:
                if symbol_package:
                    if i[0][0] == '*':
                        for node in symbol_package[int(i[0][1:])]:
                            grammar_node += self.__generate_grammar_tuple(i[1], node)
                    else:
                        for node in symbol_package[int(i[0])]:
                            grammar_node.append(self.__generate_grammar_tuple(i[1], node))
        grammar_node.reduce_number = statement_index
        return grammar_node

    def grammar_analysis(self, token_list):
        grammar = BosonGrammar()
        analysis_stack = [0]
        symbol_stack = []
        token_index = 0
        while token_index < len(token_list):
            token = token_list[token_index]
            current_state = analysis_stack[-1]
            operation = self.__action_table.get(current_state, {}).get(self.__terminal_index[token.symbol], 'e')
            operation_flag = operation[0]
            if operation_flag == 'e':
                grammar.error_index = token_index
                return grammar
            elif operation_flag == 's':
                state_number = int(operation[1:])
                analysis_stack.append(state_number)
                token_index += 1
                symbol_stack.append(token.text)
            elif operation_flag == 'r':
                statement_index = int(operation[1:]) - 1
                reduce_sum = self.__reduce_symbol_sum[statement_index]
                for _ in range(reduce_sum):
                    analysis_stack.pop()
                current_state = analysis_stack[-1]
                current_non_terminal_index = self.__reduce_to_non_terminal_index[statement_index]
                goto_next_state = self.__goto_table.get(current_state, {}).get(current_non_terminal_index, -1)
                if goto_next_state == -1:
                    raise ValueError('Invalid goto action: state={}, non-terminal={}'.format(current_state, current_non_terminal_index))
                analysis_stack.append(goto_next_state)
                if statement_index in self.__node_table:
                    symbol_package = []
                    for _ in range(reduce_sum):
                        symbol_package.insert(0, symbol_stack.pop())
                    symbol_stack.append(self.__generate_grammar_tuple(statement_index, symbol_package))
                elif statement_index in [34, 35, 36, 37, 43, 44, 46, 54, 55]:
                    grammar_node = BosonGrammarNode()
                    for _ in range(reduce_sum):
                        grammar_node.insert(0, symbol_stack.pop())
                    grammar_node.reduce_number = statement_index
                    symbol_stack.append(grammar_node)
                else:
                    raise ValueError('Invalid reduce number: reduce={}'.format(statement_index))
            elif operation_flag == 'a':
                grammar.grammar_tree = symbol_stack[0]
                return grammar
            else:
                raise ValueError('Invalid action: action={}'.format(operation))
        raise RuntimeError('Analyzer unusual exit.')


class BosonSemanticAnalyzer:
    def __init__(self):
        self.__reduce_number_to_grammar_name = {
            38: 'command',
            53: 'reduce',
            51: 'grammar_node',
            48: 'name_closure',
            47: 'literal',
            40: 'complex_closure',
            39: 'complex_optional'
        }
        self.__reduce_number_to_grammar_number = {
            49: 0,
            54: 1,
            55: 2,
            35: 4,
            34: 5,
            45: 7,
            41: 8,
            42: 9,
            43: 10,
            44: 11,
            50: 12,
            52: 13,
            46: 15,
            36: 20,
            37: 21
        }
        self.__naive_reduce_number = {34, 35, 36, 37, 42, 43, 44, 46, 47, 49, 54, 55}
        self.__semantic_entity = {}

    @staticmethod
    def __default_semantic_entity(grammar_entity):
        return grammar_entity

    @staticmethod
    def __naive_semantic_entity(grammar_entity):
        if len(grammar_entity) == 0:
            return None
        elif len(grammar_entity) == 1:
            return grammar_entity[0]
        else:
            return grammar_entity

    def __semantic_analysis(self, grammar_tree: BosonGrammarNode):
        if grammar_tree.reduce_number in self.__reduce_number_to_grammar_name:
            grammar_name = self.__reduce_number_to_grammar_name[grammar_tree.reduce_number]
        elif grammar_tree.reduce_number in self.__reduce_number_to_grammar_number:
            grammar_name = '!grammar_{}'.format(self.__reduce_number_to_grammar_number[grammar_tree.reduce_number])
        else:
            grammar_name = '!grammar_{}'.format('hidden')
        grammar_entity = list(map(lambda g: self.__semantic_analysis(g) if isinstance(g, BosonGrammarNode) else g, grammar_tree.data()))
        if grammar_name in self.__semantic_entity:
            return self.__semantic_entity[grammar_name](grammar_entity)
        if grammar_tree.reduce_number in self.__naive_reduce_number:
            return self.__naive_semantic_entity(grammar_entity)
        else:
            return self.__default_semantic_entity(grammar_entity)

    def semantic_analysis(self, grammar_tree: BosonGrammarNode):
        return self.__semantic_analysis(grammar_tree)

    def semantic_entity(self, sign):
        def decorator(f):
            if isinstance(sign, int):
                name = '!grammar_{}'.format(sign)
            elif isinstance(sign, str):
                name = sign
            else:
                raise ValueError('Invalid grammar sign: {}'.format(sign))
            self.__semantic_entity[name] = f
            return f
        return decorator
